const data ={
    products:[
        {
            name: 'Nike ',
            slug: 'nike-slim-shirt',
            category:'Shrits',
            image:'/images/converse.webp',
            price: 120,
            countInStock:10,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            descpription: 'high quality shirt',
        },
        {
            name: 'Nike Slim Pant',
            slug: 'nike-slim-pant',
            category:'Pants',
            image:'/images/newbalance.webp',
            price: 25,
            countInStock:15,
            brand:'Nike',
            rating: 4.5,
            numReviews: 14,
            descpription: 'high quality product',
        },
        {
            name: 'Adidas Fit Pnat',
            slug: 'adidas-fit-pant',
            category:'Pants',
            image:'/images/nike.webp',
            price: 65,
            countInStock:5,
            brand:'Puma',
            rating: 4.5,
            numReviews: 10,
            descpription: 'high quality product',
        },
        {
            name: 'Adidas Fit Pnat',
            slug: 'adidas-fit-pant',
            category:'Pants',
            image:'/images/nike.webp',
            price: 65,
            countInStock:5,
            brand:'Puma',
            rating: 4.5,
            numReviews: 10,
            descpription: 'high quality product',
        },
    ],
};

export default data;